services:
  nest-app:
    build: .
    command: npm run start:dev
    volumes:
      - ./test:/usr/src/app/test
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - "${CLIENT_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    environment:
      MONGODB_DBURL: mongodb://${MONGO_INITDB_USER}:${MONGO_INITDB_PWD}@db:27017/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}
      MONGODB_DBNAME: ${MONGO_INITDB_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: ${SERVER_PORT}
    networks:
      - backbone
  db:
    image: mongo:4.2.3
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PWD}
    networks:
      - backbone
networks:
  backbone:
    driver: bridge